# Generated by Django 5.2.17 on 2026-09-18 02:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import atlas.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                ("order", models.IntegerField(default=999, verbose_name="显示次序")),
            ],
            options={
                "verbose_name": "阵营",
                "verbose_name_plural": "阵营",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="邮箱")),
                ("email_verified", models.BooleanField(default=False, verbose_name="邮箱已验证")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True, verbose_name="文件摘要")),
                ("summary", models.JSONField(default=dict, verbose_name="导入统计")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "导入批次",
                "verbose_name_plural": "导入批次",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=atlas.models.person_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9_-]+$", "人物 ID 只能包含字母、数字、下划线和短横线。"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="姓名")),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[atlas.models.validate_aliases],
                        verbose_name="别名",
                    ),
                ),
                ("group_id", models.CharField(blank=True, max_length=100, verbose_name="小队 ID")),
                ("group_name", models.CharField(blank=True, max_length=120, verbose_name="小队名称")),
                ("is_operator", models.BooleanField(db_index=True, default=False, verbose_name="已实装干员")),
                ("avatar", models.CharField(blank=True, max_length=250, verbose_name="头像路径")),
                ("published", models.BooleanField(db_index=True, default=True, verbose_name="已公开")),
                ("version", models.PositiveIntegerField(default=1, editable=False, verbose_name="修订号")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.faction",
                        verbose_name="当前阵营",
                    ),
                ),
            ],
            options={
                "verbose_name": "人物",
                "verbose_name_plural": "人物",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=100, unique=True, verbose_name="游戏角色 ID")),
                ("label", models.CharField(blank=True, max_length=120, verbose_name="形态名称")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="atlas.person",
                        verbose_name="统一人物",
                    ),
                ),
            ],
            options={
                "verbose_name": "身份映射",
                "verbose_name_plural": "身份映射",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=atlas.models.relationship_id,
                        max_length=220,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("mutual", "确认相识"), ("awareness", "单向知晓")],
                        max_length=20,
                        verbose_name="判定",
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=12000, verbose_name="判定说明")),
                ("stable_keys", models.JSONField(blank=True, default=list, verbose_name="原始稳定键")),
                ("published", models.BooleanField(db_index=True, default=True, verbose_name="已公开")),
                ("version", models.PositiveIntegerField(default=1, editable=False, verbose_name="修订号")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awareness_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awareness",
                        to="atlas.person",
                        verbose_name="知晓方",
                    ),
                ),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_a",
                        to="atlas.person",
                        verbose_name="人物 A",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_b",
                        to="atlas.person",
                        verbose_name="人物 B",
                    ),
                ),
            ],
            options={
                "verbose_name": "人物关系",
                "verbose_name_plural": "人物关系",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.person",
                        verbose_name="人物",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.relationship",
                        verbose_name="关系",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quote", models.TextField(max_length=100000, verbose_name="关键原文")),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[atlas.models.validate_sources],
                        verbose_name="来源",
                    ),
                ),
                (
                    "import_key",
                    models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="atlas.relationship",
                        verbose_name="关系",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据",
                "verbose_name_plural": "证据",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(max_length=3000, verbose_name="正文")),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "公开"), ("hidden", "已隐藏"), ("deleted", "作者删除")],
                        db_index=True,
                        default="visible",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.person",
                        verbose_name="人物",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.relationship",
                        verbose_name="关系",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["-created_at", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="原因")),
                ("resolved", models.BooleanField(default=False, verbose_name="已处理")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="atlas.comment", verbose_name="评论"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论举报",
                "verbose_name_plural": "评论举报",
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_type", models.CharField(max_length=40, verbose_name="对象类型")),
                ("target_id", models.CharField(max_length=250, verbose_name="对象 ID")),
                ("before", models.JSONField(default=dict, verbose_name="修改前")),
                ("after", models.JSONField(default=dict, verbose_name="修改后")),
                ("reason", models.CharField(max_length=300, verbose_name="来源")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "修改记录",
                "verbose_name_plural": "修改记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(max_length=6000, verbose_name="补充说明")),
                (
                    "evidence_text",
                    models.TextField(blank=True, max_length=12000, verbose_name="补充原文与来源"),
                ),
                (
                    "proposed_changes",
                    models.JSONField(blank=True, default=dict, verbose_name="审核后拟应用的修改"),
                ),
                ("base_version", models.PositiveIntegerField(verbose_name="提交时修订号")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("approved", "已采纳"), ("rejected", "未采纳")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("review_note", models.TextField(blank=True, max_length=3000, verbose_name="审核意见")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.person",
                        verbose_name="人物",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.relationship",
                        verbose_name="关系",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资料补充",
                "verbose_name_plural": "资料补充",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(fields=("person_a", "person_b"), name="unique_person_pair"),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("person_a_id__lt", models.F("person_b_id"))), name="ordered_distinct_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("awareness_from__isnull", True), ("kind", "mutual")),
                    models.Q(
                        ("awareness_from__isnull", False),
                        ("kind", "awareness"),
                        models.Q(
                            ("awareness_from", models.F("person_a")),
                            ("awareness_from", models.F("person_b")),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="valid_awareness_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", False), ("relationship__isnull", True)),
                    models.Q(("person__isnull", True), ("relationship__isnull", False)),
                    _connector="OR",
                ),
                name="favorite_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(fields=("user", "person"), name="unique_person_favorite"),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "relationship"), name="unique_relationship_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", False), ("relationship__isnull", True)),
                    models.Q(("person__isnull", True), ("relationship__isnull", False)),
                    _connector="OR",
                ),
                name="comment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(fields=("comment", "reporter"), name="unique_comment_report"),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", False), ("relationship__isnull", True)),
                    models.Q(("person__isnull", True), ("relationship__isnull", False)),
                    _connector="OR",
                ),
                name="submission_exactly_one_target",
            ),
        ),
    ]
