# Generated by Django 5.2.17 on 2026-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atlas", "0002_rhodes_elite_factions"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="avatar_is_generic",
            field=models.BooleanField(default=False, verbose_name="通用立绘"),
        ),
        migrations.AddField(
            model_name="person",
            name="avatar_source",
            field=models.URLField(blank=True, max_length=1500, verbose_name="头像来源"),
        ),
    ]
