# Generated by Django 5.2.17 on 2026-09-20 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_npc_avatar_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGuard',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FeedbackReceipt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('data_error', '资料纠错'), ('source', '来源补充'), ('addition', '资料补充'), ('site_issue', '网站问题'), ('other', '其他')], max_length=20, verbose_name='问题类型')),
                ('description', models.TextField(max_length=6000, verbose_name='说明')),
                ('source_url', models.CharField(blank=True, max_length=1500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='来源链接')),
                ('contact', models.CharField(blank=True, max_length=254, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('linked', '已关联 Issue/PR'), ('duplicate', '重复'), ('resolved', '已解决'), ('rejected', '不采纳')], default='pending', max_length=20, verbose_name='处理状态')),
                ('review_note', models.TextField(blank=True, max_length=6000, verbose_name='处理理由/内部备注')),
                ('issue_url', models.CharField(blank=True, max_length=1500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='关联 Issue/PR')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='收到时间')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.person', verbose_name='人物')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.relationship', verbose_name='关系')),
            ],
            options={
                'verbose_name': '访客反馈',
                'verbose_name_plural': '访客反馈',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('view_feedback_contact', 'Can view feedback contact details')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='atlas.feedback')),
            ],
            options={
                'verbose_name': '反馈处理记录',
                'verbose_name_plural': '反馈处理记录',
                'ordering': ['created_at', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', True), ('relationship__isnull', True), _connector='OR'), name='feedback_at_most_one_target'),
        ),
    ]
