# Generated by Django 5.2.17 on 2026-09-20 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_release_state(apps, schema_editor):
    apps.get_model('atlas', 'ReleaseState').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_anonymous_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='published',
            field=models.BooleanField(default=True, verbose_name='已公开'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_id',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True, verbose_name='Git 证据 ID'),
        ),
        migrations.AddField(
            model_name='identity',
            name='published',
            field=models.BooleanField(default=True, verbose_name='已公开'),
        ),
        migrations.CreateModel(
            name='DataRelease',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='发布版本')),
                ('package_digest', models.CharField(max_length=64, verbose_name='发布包摘要')),
                ('manifest', models.JSONField(verbose_name='发布清单')),
                ('formal_snapshot', models.JSONField(verbose_name='正式资料基线')),
                ('narratives', models.JSONField(verbose_name='条件叙事与来源记录')),
                ('changes', models.JSONField(verbose_name='发布差异')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='应用时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.datarelease')),
            ],
            options={
                'verbose_name': '资料发布',
                'verbose_name_plural': '资料发布',
                'ordering': ('-created_at',),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ReleaseState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.datarelease')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_release_state')],
            },
        ),
        migrations.RunPython(create_release_state, migrations.RunPython.noop),
    ]
