# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_versioned_data_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('people', '人物'), ('factions', '阵营'), ('identities', '身份映射'), ('relationships', '关系'), ('evidence', '独立证据')], max_length=20, verbose_name='资料类型')),
                ('record_id', models.CharField(max_length=250, verbose_name='稳定 ID')),
                ('base_digest', models.CharField(max_length=64, verbose_name='基线摘要')),
                ('before', models.JSONField(null=True, verbose_name='修改前')),
                ('proposed', models.JSONField(verbose_name='候选内容')),
                ('private_note', models.TextField(blank=True, max_length=6000, verbose_name='私有编辑备注')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='候选版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('base_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atlas.datarelease', verbose_name='基线发布')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_candidates', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
            ],
            options={
                'verbose_name': '资料候选',
                'verbose_name_plural': '资料候选',
                'ordering': ('-updated_at', '-pk'),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CandidateEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('proposed', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='atlas.candidate')),
            ],
            options={
                'ordering': ('version',),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('candidate', 'version'), name='candidate_edit_version')],
            },
        ),
    ]
