# Generated by Django 5.2.17 on 2026-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_data_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginGuard',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
