# Generated by Django 5.2.17 on 2026-09-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_admin_login_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='included',
            field=models.BooleanField(default=True, verbose_name='纳入修订'),
        ),
        migrations.AddField(
            model_name='datarelease',
            name='origin',
            field=models.CharField(choices=[('git', '初始资料包'), ('editorial', '后台修订'), ('rollback', '后台回退')], default='git', max_length=20, verbose_name='发布来源'),
        ),
        migrations.AddField(
            model_name='releasestate',
            name='authority',
            field=models.CharField(choices=[('git', '初始资料包'), ('database', '后台管理')], default='git', max_length=20),
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='修订标题')),
                ('description', models.TextField(blank=True, max_length=6000, verbose_name='修改说明与依据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('approved', '已通过'), ('published', '已发布'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='修订版本')),
                ('review_note', models.TextField(blank=True, max_length=6000, verbose_name='审核意见')),
                ('review_digest', models.CharField(blank=True, max_length=64)),
                ('asset_version', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='atlas.datarelease', verbose_name='基线发布')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_sets', to='atlas.feedback', verbose_name='关联反馈')),
                ('published_release', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_set', to='atlas.datarelease', verbose_name='发布版本')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('rollback_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='atlas.datarelease', verbose_name='回退目标')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后操作人')),
            ],
            options={
                'verbose_name': '资料修订',
                'verbose_name_plural': '资料修订',
                'ordering': ('-updated_at', '-pk'),
                'permissions': (('review_changeset', 'Can review editorial changes'), ('publish_changeset', 'Can publish editorial changes')),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='change_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='atlas.changeset', verbose_name='所属修订'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('change_set', 'section', 'record_id'), name='unique_changeset_record'),
        ),
        migrations.AddField(
            model_name='changesetevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changesetevent',
            name='change_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='atlas.changeset'),
        ),
    ]
