# Generated by Django 5.2.17 on 2026-09-23 07:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_editorial_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_hash', models.CharField(max_length=64, unique=True)),
                ('risk_status', models.CharField(default='accepted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_ids', models.JSONField(default=list)),
                ('favorite_ids', models.JSONField(default=list)),
                ('support_version', models.PositiveIntegerField(default=0)),
                ('support_modified_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': '喜好参与标识',
                'permissions': [('review_preference_risk', 'Can review preference risk')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceRate',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceCatalog',
            fields=[
                ('version', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('base_version', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preference_catalogs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preference_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '喜好候选名录',
                'permissions': [('review_preference_catalog', 'Can review preference catalog'), ('publish_preference_catalog', 'Can publish preference catalog')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceControl',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('reads_enabled', models.BooleanField(default=True)),
                ('writes_enabled', models.BooleanField(default=True)),
                ('tasks_enabled', models.BooleanField(default=True)),
                ('supports_enabled', models.BooleanField(default=True)),
                ('choices_enabled', models.BooleanField(default=True)),
                ('paused_objects', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('last_aggregation_at', models.DateTimeField(null=True)),
                ('aggregation_error', models.TextField(blank=True)),
                ('retained_since', models.DateTimeField(null=True)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.preferencecatalog')),
            ],
            options={
                'verbose_name': '喜好运行开关',
            },
        ),
        migrations.CreateModel(
            name='PreferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=220)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.preferenceparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceRiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('signal', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.preferenceparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('digest', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.preferenceparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'key'), name='preference_operation_unique')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('object_id', models.CharField(max_length=220)),
                ('choice_id', models.CharField(blank=True, max_length=220)),
                ('action', models.CharField(default='withdraw', max_length=16)),
                ('catalog_version', models.CharField(blank=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=0)),
                ('modified_at', models.DateTimeField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.preferenceparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'kind', 'object_id'), name='preference_one_current_choice')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('object_id', models.CharField(blank=True, max_length=220)),
                ('window', models.PositiveIntegerField(default=0)),
                ('cutoff', models.DateTimeField(db_index=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_version', models.CharField(max_length=120)),
                ('algorithm_version', models.CharField(max_length=100)),
                ('asset_version', models.CharField(max_length=120)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('supersedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.preferencesnapshot')),
            ],
            options={
                'ordering': ['-cutoff', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id', 'window', 'cutoff', 'revision'), name='preference_snapshot_run_unique')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_id', models.CharField(max_length=220)),
                ('right_id', models.CharField(max_length=220)),
                ('pair_key', models.CharField(max_length=450)),
                ('strategy', models.CharField(max_length=40)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(db_index=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=16)),
                ('winner_id', models.CharField(blank=True, max_length=220)),
                ('risk_status', models.CharField(default='accepted', max_length=16)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atlas.preferencecatalog')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.preferenceparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'issued_at'], name='atlas_prefe_partici_43a997_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('participant',), name='preference_one_pending_task'), models.CheckConstraint(condition=models.Q(('left_id', models.F('right_id')), _negated=True), name='preference_distinct_people')],
            },
        ),
    ]
