# Generated by Django 5.2.17 on 2026-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0009_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencesnapshot',
            options={'ordering': ['-cutoff', '-revision', '-pk']},
        ),
        migrations.RemoveConstraint(
            model_name='preferencesnapshot',
            name='preference_snapshot_run_unique',
        ),
        migrations.AddConstraint(
            model_name='preferencesnapshot',
            constraint=models.UniqueConstraint(fields=('kind', 'object_id', 'window', 'cutoff', 'catalog_version', 'algorithm_version', 'revision'), name='preference_snapshot_run_unique'),
        ),
    ]
