# Generated by Django 5.2.17 on 2026-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0010_preference_snapshot_catalog_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preferencesnapshot',
            name='preference_snapshot_run_unique',
        ),
        migrations.AddField(
            model_name='preferenceparticipant',
            name='subject_favorite_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferenceparticipant',
            name='subject_support_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferencesnapshot',
            name='scope',
            field=models.CharField(default='person', max_length=12),
        ),
        migrations.AddField(
            model_name='preferencetask',
            name='left_subject_id',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='preferencetask',
            name='right_subject_id',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='preferencetask',
            name='pair_key',
            field=models.CharField(max_length=490),
        ),
        migrations.AddConstraint(
            model_name='preferencesnapshot',
            constraint=models.UniqueConstraint(fields=('scope', 'kind', 'object_id', 'window', 'cutoff', 'catalog_version', 'algorithm_version', 'revision'), name='preference_snapshot_run_unique'),
        ),
    ]
