# Generated by Django 5.2.17 on 2026-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0011_preference_identity_scopes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preferenceevent',
            index=models.Index(fields=['participant', 'object_id', '-created_at', '-id'], name='preference_event_anchor_idx'),
        ),
    ]
