# Generated by Django 5.2.17 on 2026-09-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0012_preference_event_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='使用英文、数字和短横线，保存后不再改动。', max_length=100, unique=True, verbose_name='稳定标识')),
                ('category', models.CharField(choices=[('story', '剧情修订'), ('feature', '功能更新')], max_length=16, verbose_name='分类')),
                ('title', models.CharField(max_length=140, verbose_name='标题')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('changes', models.TextField(help_text='每行一项变化，使用纯文本。', max_length=16000, verbose_name='更新内容')),
                ('acknowledgements', models.TextField(blank=True, help_text='仅填写可公开的感谢文案；具名致谢前确认对方同意，不粘贴联系方式。', max_length=1000, verbose_name='感谢反馈')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('version', models.PositiveIntegerField(default=1)),
                ('data_release', models.ForeignKey(blank=True, help_text='剧情修订发布前必须关联实际发布的资料版本。', null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.datarelease', verbose_name='关联资料版本')),
            ],
            options={
                'verbose_name': '更新说明',
                'verbose_name_plural': '更新说明',
                'ordering': ('-published_at', '-pk'),
                'permissions': (('publish_siteupdate', '可以发布或撤回更新说明'),),
            },
        ),
    ]
